---
version: '3.8'

services:
  postgres:
    image: postgres:18.1
    volumes:
      - postgres_data:/var/lib/postgresql/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  fastapi:
    image: pi-security-cam-fastapi
    build:
      context: ./server/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_TYPE: ${DB_TYPE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
